animal_app/urls.py
from django.urls import path
from . import views


app_name = 'animal_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict')
]

django_animal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animal_app.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animal_app/models.py
from django.db import models
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
from PIL import Image
import io, base64


graph = tf.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

    classes = ['lion', 'tiger', 'cheetah']
    MODEL_FILE_PATH = './animal_app/ml_models/animal_cnn.h5'
    num_classes = len(classes)
    image_size = 50

    # 引数から画像ファイルを参照して読み込む
    def predict(self):
        image = None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)
            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)
            image = Image.open(img_bin)
            image = image.convert('RGB')
            image = image.resize((self.image_size, self.image_size))
            data = np.asarray(image)
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            return self.classes[predicted], percentage
    

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img

animal_app/forms.py
from django import forms
from .models import Photo


class PhotoForm(forms.ModelForm):
    # image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}))
    class Meta:
        model = Photo
        fields = ('image',)

animal_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo


def index(request):
    template = loader.get_template('animal_app/index.html')
    context = {'form': PhotoForm()}
    return HttpResponse(template.render(context, request))


def predict(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            photo = Photo(image=form.cleaned_data['image'])
            
            predicted, percentage = photo.predict()
            
            template = loader.get_template('animal_app/result.html')
            context = {
                'photo_name': photo.image.name,
                'photo_data': photo.image_src(),
                'predicted': predicted,
                'percentage': percentage,
            }
            return HttpResponse(template.render(context, request))
        else:
            raise ValueError('Formが不正です')
    return redirect('animal_app:index')

animal_app/templates/animal_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type='text/css' href="{% static 'css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <title>animalAI</title>
  </head>
  <body style="background-image: url('https://s2.best-wallpaper.net/wallpaper/1920x1200/1806/Savannah-Africa-zebras-at-sunset_1920x1200.jpg'); background-size: cover;">
    <nav class='navbar navbar-expand-lg navbar-light navbar-dark '>
        <a class='navbar-brand' href="{% url 'animal_app:index' %}">どうぶつはんていAIアプリ</a>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
  </body>
</html>

animal_app/templates/animal_app/index.html
{% extends 'animal_app/base.html' %}


{% block content %}
<div style='color: white'>
    <h4 class='mt-4 mb-5 border-bottom'>どうぶつはんていAIアプリ</h4>
    <p>ライオン、トラ、チーターのしゃしんをえらんですいていボタンをクリックしてね！</p>
    <form action="{% url 'animal_app:predict' %}" method='POST' class='form' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <div class="custom-file">
                {{ form.image }}
                <!-- <label for="customFile" class="custom-file-label">
                    すいていしたいファイルをえらんでね！
                </label> -->
            </div>
        </div>
        <button type='submit' class='save btn btn-primary'>すいていする</button>
    </form>
</div>
{% endblock %}

animal_app/templates/animal_app/result.html
{% extends 'animal_app/base.html' %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom" style='color: white;'>animalAI推定結果</h4>

    <table class='table' style='color: white;'>
        <tbody>
            <tr>
                <td>ファイル名</td>
                <td>{{ photo_name }}</td>
            </tr>
            <tr>
                <td>画像ファイル</td>
                <td><img class="preview-img" src={{ photo_data }}></td>
            </tr>
            <tr>
                <td>推定ラベル</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr>
                <td>推定確率</td>
                <td>{{ percentage }} %</td>
            </tr>
        </tbody>
    </table>

    <a href="{% url 'animal_app:index' %}" class='btn btn-secondary'>画像選択メニューに戻る</a>

</div>
{% endblock %}